### ISSUE TITLE
cilogon uses email address instead of username

### ISSUE THREAD

**Issue by davidedelvento** [jupyterhub/oauthenticator#114]
It looks like `oauthenticator/cilogon.py` is setting the jupyterhub username to the email address the user has registered (with '@' replaced by '.')

Just to be clear, I'm talking about the code block starting [here](https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/cilogon.py#L184)

It looks like this code is pulling the user's email address out of the CILogon certificate subjectAltName. I'm using cilogon for letting (selected) people with XSEDE credentials login into the jupyter service I'm building. For my own reasons, I create accounts manually. When I started, I thought this was a minor nuisance, but this is becoming a growing problem for me, for several reasons:

* (medium) people do not remember the email address they associated with XSEDE. So I can't simply create an account for them when they ask (giving me their XSEDE username): they either have to check that email (and apparently everybody gets it wrong, not sure why) or they have to attempt login and I have to look at the logs, identify their email, and create an username with that email address (with '@' replaced by '.') -- a 10 minutes affair becomes a multi-day back-and-forth email conversation, explain this and that, digging into the logs, huge waste of time

* (major): if users need to change the email address associated with XSEDE, their account on my system because inaccessible.

* (minor): creating usernames with "." is discouraged on linux (however  `--force-badname` allows them to exist and POSIX do not forbid them in IEEE Std 1003.1-2001)

* (minor, unless actually encountered, when it will become major): users with email `john@smith.domain.com` and `john.smith@domain.com` would both resolve to the same username `john.smith.domain.com`

It looks like the code block starting [here](https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/cilogon.py#L184) should get the `eduPersonPrincipalName` instead, which is always username@xsede.org for XSEDE users (and then the `@xsede.org` part could be either removed or made into `.xsede.org` as it is now)

For the (extremely limited) tests I have done, this could be accomplished by replacing [line 184](https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/cilogon.py#L184) with

```
  if ext.get_short_name().decode('ascii', 'replace') == '1.3.6.1.4.1.5923.1.1.1.6':
```

however that seems too much hard-coded numbers to be generic and I don't know much about CILogon or OAuth to know if that's a valid thing to do (otherwise this would be a pull request :) )

I was also told:

> The better long-term fix is to update oauthenticator/cilogon.py to use OAuth2 rather than OAuth1. Then it won't need to mess with certificates at all, because CILogon's OAuth2 interface (http://www.cilogon.org/oidc) provides all the user info in JSON.

but I don't know anything about it.

**Comment by jbasney** [comment]
Thanks @davidedelvento for opening this issue. On behalf of the CILogon project, I endorse both the one-line short-term fix and the long-term fix of updating to OIDC/OAuth2. We're finding `oauthenticator/cilogon.py` to be a popular option for connecting to SAML identity providers via CILogon.

Regarding the one-line fix, the `1.3.6.1.4.1.5923.1.1.1.6` OID is specified at http://macedir.org/specs/eduperson/#eduPersonPrincipalName and is the proper way to reference the `eduPersonPrincipalName` attribute that is widely used in [R&E SAML federations](https://technical.edugain.org/) and is the recommended user identifier for these federations.

One caveat is that CILogon also supports authentication with Google and GitHub, and since they're not SAML identity providers, CILogon can't provide an `eduPersonPrincipalName` attribute for them. It may be better to use `oauthenticator/google.py` and/or `oauthenticator/github.py` directly for those identity providers rather than supporting them through CILogon.

For the long-term fix of updating to OIDC/OAuth2, the `org.cilogon.userinfo` scope provides an `eppn` claim in the JSON response as documented at http://www.cilogon.org/oidc so there's no need to mess with X.509 OIDs in that case.

Sorry we don't have Python developers on the CILogon team, but otherwise we're happy to help any way we can (for example, with testing).

**Comment by willingc** [comment]
Thanks @davidedelvento and @jbasney.

@minrk Would you mind taking a look? I'm traveling today and then off for a few days :-)

**Comment by minrk** [comment]
Since everything else in OAuthenticator is already using OAuth2, updating to OAuth2 is what we should do. This should be a small task once I have a test setup.

**Comment by jbasney** [comment]
I think this issue is fixed by #121.

**Comment by willingc** [comment]
Great. Thanks @jbasney for the heads up.

I'll close this. If folks find that something hasn't been addressed, please leave a message here or open a new issue. Thanks!

**Comment by davidedelvento** [comment]
Please see also #133 which is related to this
