### ISSUE TITLE
Import of azuread module fails due to missing file when installing with pip3

### ISSUE THREAD

**Issue by psnx** [jupyterhub/oauthenticator#195]
When I  install the package the way it is described in the `README.md` the `azuread.py` is not copied into the destination folder, which in my case is `~/anaconda3/lib/python3.6/site-packages/oauthenticator`
The way of installation was according to `README.md`
```bash
git clone https://github.com/jupyterhub/oauthenticator.git
cd oauthenticator
pip3 install -e .
```
I copied the missing file into the package folder manually, so the import now works. I propose that the installer be updated in order to include the `azuread.py` file.

**Comment by minrk** [comment]
`pip install -e` doesn't copy any files, it does a dev-install by creating `site-packages/oauthenticator.egg-link` referring to the checkout directory. If there is an `oauthenticator` directory in site-packages, it is from a previous install, which might be why there are not files from the dev version there.

If you want to install oauthenticator to site-packages instead of an "editable" install, use `pip install .` instead of `pip install -e .` If you install the current dev version, it will include azuread.py
