### ISSUE TITLE
Using Auth0 subdomain without using ENV variables

### ISSUE THREAD

**Issue by JuanCab** [jupyterhub/oauthenticator#205]
I am trying to use the oauthenticator plugin in TLJH which allows you to set variables but has no clear mechanism for defining environmental variables for the instance of JupyterHub.  From reviewing the source code for the Auth0 authenticator at 

https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/auth0.py

it seems that the only way to set the Auth0 subdomain value to use is via an environmental variable AUTH0_SUBDOMAIN.  Is there no other mechanism to do this via jupyterhub_config.py?

**Comment by minrk** [comment]
Indeed, this (and all other env-only config, which is ~only setting provider URLs, I think) should be settable via a regular traitlet. They are not currently due to an implementation detail that these particular values are configured prior to when traitlets get a chance to intervene, due to the mixin API  we started out with. But that's a solvable problem.

In the meantime, you can always set environment variables in jupyterhub_config.py:

```python
import os
os.environ['AUTH0_SUBDOMAIN'] = 'mysubdomain'
```

That's AOK, and I wouldn't even describe it as a workaround. It's a totally valid thing to do.
