### ISSUE TITLE
Environment variable OAUTH2_AUTHENTICATION_PARAMS is parsed incorrectly

### ISSUE THREAD

**Issue by mhuttner** [jupyterhub/oauthenticator#208]
It is parsed here:
https://github.com/jupyterhub/oauthenticator/blob/8277ae61f471fac5c054b1e7980da00c84ed3c4e/oauthenticator/generic.py#L62-L65
I see no way to set this, os.environ.get will always return a string (if the variable exists) and 
the Dict constructor expects a python dict

Is the some special string formatting i have to use?
I think the code should be something like this:
```python
userdata_params = Dict( 
     json.loads(os.environ.get('OAUTH2_USERDATA_PARAMS', '{}')), 
     help="Userdata params to get user data login information" 
 ).tag(config=True) 
```

**Comment by minrk** [comment]
I guess nobody's used that before! JSON seems sensible to me.

**Comment by minrk** [comment]
To be clear, I guess that anyone using this is using the standard configuration format:

```python
c.GenericOAuthenticator.userdata_params = {'foo': 'bar'}
```

in jupyterhub_config.py.

and not setting it via environment variable. Not everything should be an environment variable, and I think probably only. I think there's been some misunderstanding in contributed authenticators that *everything* should be set with environment variables, which isn't true.

I think that maybe the best answer for #209 is to instead remove the mention of environment variables for these config values, since it's never worked.

**Comment by mhuttner** [comment]
I stumbled upon these Variables because I wanted to set the openid scopes, but these can already be set using the scopes parameter. So even though I created the PR with the fix I later found no reason to
use them. 
I agree, the best fix is probably to just delete them.
