### ISSUE TITLE
Tenant_id is missing in Authorize url for Azure AD and Jupyterhub in docker container

### ISSUE THREAD

**Issue by manm05** [jupyterhub/oauthenticator#258]
I have installed Jupyterhub in a docker container and trying to integrate it with Azure AD for Authentication purpose. For this,   I have followed [https://github.com/jupyterhub/oauthenticator ]
and added the required configurations in my jupyterhub_config.py file. But, once I click on 'Login with Azure AD' button, it redirects to me below url 
[https://login.microsoftonline.com//oauth2/authorize]

Here the url is missing tenant_id. If I include the tenant_id manually in the url as below, it works fine
[https://login.microsoftonline.com/<tenant_id>/oauth2/authorize]

There is a similar issue resolved at [https://github.com/jupyterhub/oauthenticator/issues/218], but that is for Jupyterhub with Kubernetes. I also tried similar thing and created and added config details in a config.yaml file as mentioned in the above link, but no luck.
Could you please tell me how can I resolve this issue ?  Any help will be appreciated. 
Mu jupyterhub_config.py file looks like below:-

`import os
from oauthenticator.azuread import AzureAdOAuthenticator
c.JupyterHub.authenticator_class = AzureAdOAuthenticator

c.Application.log_level = 'DEBUG'

c.AzureAdOAuthenticator.tenant_id = os.environ.get('AAD_TENANT_ID')    #exported #AAD_TENANT_ID as envirnment variable

c.AzureAdOAuthenticator.tenant_id = 'XXXXXXXX'           # added this explicitely

c.AzureAdOAuthenticator.oauth_callback_url = 'XXXXXXXXXXXXXX'

c.AzureAdOAuthenticator.client_id = 'XXXXXXX'
c.AzureAdOAuthenticator.client_secret = 'XXXXXXXXXXXXX'
`

**Comment by timlod** [comment]
I am not using the DockerSpawner, but ran into the same trouble using the LocalProcessSpawner at some point.
The issue is that the environment variable AAD_TENANT_ID was not accessible - the export made it available locally, but not from wherever jupyterhub or the single notebookserver was started.

I ended up fixing it by appending the env variable to /etc/environment.
I think that's not the best solution, but a quick fix.
For the DockerSpawner, try to look into passing the tenant ID into the container as an environment variable, perhaps it will fix your problem.

**Comment by manm05** [comment]
Thanks Tim for that. It got resolved by exporting the environment variable AAD_TENANT_ID before importing AzureAdOAuthenticator class in the jupyter_config.py file.

**Comment by manics** [comment]
Sounds like this was resolved.
