### ISSUE TITLE
Default email address username normalization for GoogleOAuthenticator is security risk

### ISSUE THREAD

**Issue by elibixby** [jupyterhub/oauthenticator#37]
`GoogleOAuthenticator` simply removes the Google Domain from the email to produce the returned username. This is a security risk because it allows users with the same username in different domains (if domain is unrestricted) to access the same notebook, or even access the Jupyterhub admin console.

e.g.
`admin@alice.com` is an admin user with access, `admin@bob.com` will be able to log in with the same user name.

IIUC solution is to use `Authenticator.normalize_username` and `Authenticator.validate_username` instead. Allowing displayed usernames to differ from the usernames used in proxy tables.

**Comment by minrk** [comment]
`@alice.com` is only removed if you have set

    GoogleOAuthenticator.hosted_domain = 'alice.com'

in which case only alice.com users are allowed access as `admin`, since the `@alice.com` is redundant. Otherwise, the full email address is the username.

`Authenticator.normalize_username` and `Authenticator.validate_username` are used via `Authenticator.get_authenticated_user`.

Is this not the behavior you are seeing?

**Comment by elibixby** [comment]
My mistake. Misreading of the method.
