### ISSUE TITLE
Implicit oauth2

### ISSUE THREAD

**Issue by e2raptor** [jupyterhub/oauthenticator#39]
Hi, I've been trying to implement my own authenticator against an API that uses implicit Oauth2, it means that I don't have a service to request the token, but instead, when I request the authorize service, my own redirect (I'm using the specified on the README: localhost:8000/hub/oauth_callback) comes with the access_token. To be more explicit:

Authorize url:
https://oauth2server/authorize?response_type=token&redirect_uri=http://localhost:8000/hub/oauth_callback&client_id=the_clientid&scope=read

This is the response header for that request:
http://localhost:8000/hub/oauth_callback#access_token=theaccesstoken&token_type=bearer&expires_in=108

My question is: Is there a way to implement my own oauthenticator with this type of oauth2 grant? The authenticators you already (github, google, bitbucket) always use the explicit way. Thanks in advance

**Comment by minrk** [comment]
It's definitely possible, but it's going to need a little help.

Since implicit authorization only provides the auth info to the page via `location.hash` instead of sending it to the server via url query parameters, to work with JupyterHub, you are going to need to serve an HTML page with some javascript that takes the auth info from `location.hash` and sends it to the server. That means you need three handlers instead of two:

1. login handler, redirecting to auth URL (same as existing OAuthenticator LoginHandlers)
2. at redirect_url, serve an HTML page that runs a little javascript to send `location.hash` to the server. This could be a one-line page that does something like redirect removing `#` in favor of `?`.
3. a third handler that authorizes the user. This should be almost the same, if not the same, as the OAuthHandlers in oauthenticator.

**Comment by e2raptor** [comment]
You're right, the thing is that the fragment after the hash (#) is never sended to tornado. Your answer is exactly what I need. Thanks.
