### ISSUE TITLE
Implement Gitea OAuth2 identity provider

### ISSUE THREAD

**Issue by kevung** [jupyterhub/oauthenticator#397]
Implement Gitea as identity provider.
Gitea provides OAuth2 authentification : https://docs.gitea.io/en-us/api-usage/

**Comment by manics** [comment]
Hi!
We're not accepting new Oauth providers in this repository due to the maintenance burden. There's a generic handler you might be able to configure:
https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/generic.py

If that doesn't work you can subclass it in your own Python package.

If you need more help please ask on the [community forum](https://discourse.jupyter.org/) 😀.
