### ISSUE TITLE
Discussion: don't default to allowing all users?

### ISSUE THREAD

**Issue by manics** [jupyterhub/oauthenticator#609]
### Proposed change
Don't default to allowing all users to login.

### Alternative options
Leave unchanged

### Who would use this feature?
Sysadmins who expect a "secure by default" configuration

### (Optional): Suggest a solution
As mentioned in https://github.com/jupyterhub/the-littlest-jupyterhub/issues/884 authenticators default to allowing anyone to login. Whilst this has been the case for a while it'd be safer to default to no-one unless explicitly configured, e.g. with a new configurable, or perhaps by using a special placeholder such as `allowed_users = "*"` (deliberately overriding the configurable to be list-or-string to allow this placeholder string).

The big downside is it's a breaking change, but with the changes in https://github.com/jupyterhub/oauthenticator/pull/594 now might be a good time to do this.

**Comment by manics** [comment]
I think it was justified for JupyterHub as originally designed where users also had to have system accounts first- it's reasonable that if a user can login to a system they should have JupyterHub access since they could just run Jupyter notebook from their login shell anyway.

It's much more of a problem for other authenticators, especially ones like GitHub and Google which allow millions of users by default. There are cases where this is intended (e.g. public JupyterHubs which are open to everyone but want some form of identification) but it's unlikely to be what most admins want.

On balance I think changing the upstream default for consistency is justified (and maybe override it in PamAuthenticator only?), but that's a separate discussion. As long as this OAuthenticator change can be directly ported to the parent authenticator there's no downside to making the change here first.

**Comment by Bougakov** [comment]
As the original issues' author I'd suggest adding a fix to the GitHub and Google Auth methods, not the parent method. It will solve the security implications on a wide scale, but won't add headaches to the admins deploying JupyterHub in the walled corporate or university environments.

An edge case here would be the corporate or free legacy users of https://workspace.google.com - but these orgs/individuals living in the cloud are better to be set safe than sorry by default.

Current setup can inflict serious pain on the individuals. My experience shows that JH+GoogleAuth installs are targeted by a crypto miners, maybe in an automated manner. I was lucky I have a tiny machine with 1 gig of RAM and a shared CPU. If I were renting a machine with ten Nvidia A100 I'd be in the red for thousands of dollars just in the time it took to figure out what's happening.

**Comment by Bougakov** [comment]
But anyway the issue for now deserves an explicit warning in the docs about the security implications, on the same page in the Google Auth and GitHub tutorials. When I followed the manual, it didn't ring any bells that not just the people I've added as admins would have access. Indeed, the reference mentions it, but in a spirit of _"on display in the bottom of a locked filing cabinet stuck in a disused lavatory with a sign on the door saying ‘Beware of the Leopard.”"_

**Comment by minrk** [comment]
I think it's reasonable to change the default in oauthenticator, but probably not upstream.

I agree that it should be communicated better (beyond the warning you already get on every Hub start when this is the case), but I'm not sure I agree the default should change. At least at the Hub level. Maybe my use cases are weird, but I've almost exclusively deployed hubs with GitHub oauth without limiting users, or with institutional providers where all authenticated users should be allowed.

Certainly with PAM (the default Authenticator) allowing any successful login is the most logical and least surprising behavior, not the other way around, and I think that's true for most Authenticator implementations _other_ than oauthenticator.

I do recognize that it's reasonable to be surprised that once _some_ users are specified (I.e. an admin list), that regular users aren't limited yet.

I think it is an issue mostly specific to oauthenticator and not Authenticators in general that it is likely users who successfully authenticate should not be allowed, so that makes me think if it should change, oauthenticator is the place to make allow_all_authenticated opt-in instead of opt-out, which seems a reasonable, safer default and only a very minor inconvenience for folks who want to opt-in to the current default behavior.

**Comment by consideRatio** [comment]
I hear agreement on changing the default behavior here, which I also agree with.

Following discussion upstream in jupyterhub/jupyterhub related to adding a config like this in the base class https://github.com/jupyterhub/jupyterhub/issues/4484#issuecomment-1592894022, I suggest we move onwards with a new config called `allow_all` that we implement and declare False.
