### ISSUE TITLE
Prepare 0.6.1 release

### ISSUE THREAD

**Issue by willingc** [jupyterhub/oauthenticator#89]
- [x] Update changelog
- [x] Double check README docs
- [x] Run through the [release checklist](https://github.com/jupyterhub/jupyterhub/blob/master/CHECKLIST-Release.md) and release
- [ ] Notify jupyter mailing list

cc/ @minrk

**Comment by yuvipanda** [comment]
Awesome!

Is this going to be JupyterHub 0.8 only or will it also be compatible with 0.7.2?

**Comment by minrk** [comment]
oauthenticator 0.6 still supports 0.7.

**Comment by yuvipanda** [comment]
Since auth_state is such a big feature for 0.8, I propose:

1. We release oauthenticator, with support for 0.7+
2. Next version of oauthenticator will *not* have support for 0.7, will require 0.8. 

I think this lets us clean up the code a bunch after 0.6 is cut. What do you think, @minrk? Or do you think we should strive to keep backwards compat with 0.7 for much longer?

**Comment by willingc** [comment]
To clarify @yuvipanda's proposal for others:

- OAuthenticator 0.6 will support JupyterHub 0.7+ (ideally 0.7.2+).
- OAuthenticator 0.7 would support JupyterHub 0.8+. 

My thoughts: 

As for continuing JupyterHub 0.7 support in this release, I suspect it depends on the timing of OAuthenticator 0.7 and the release of JupyterHub 0.8. If OAuthenticator is targeted for 6 months or more after JupyterHub 0.8 release, I think dropping JupyterHub 0.7 support is fine. Less than 6 months, I think we need to ask ourselves what those using JupyterHub 0.7 in production (HPC, Education) would find reasonable.

My recommendation:

- Adopt Yuvi's approach
- Release OAuthenticator 0.6 with a release note stating that this release will be the last supporting JupyterHub 0.7.
- Monitor community feedback

**Comment by minrk** [comment]
I forgot to comment here (and email the list) - 0.6 is out last week, after merging #90. I think we're already talking about 0.7 here, but the point remains valid. Since Yuvi fixed some mediawiki things that were broken in 0.6, I think we should do an 0.6.1 this week.

I think the six month timeline is good as a minimum. Maintaining support for 0.7 should not be difficult, so I think we should keep it as long as it doesn't cause trouble. Mainly it's a matter of being careful when adopting new features.

The real missing feature is a test that exercises JupyterHub's actual login flow, so we can verify that we aren't breaking it.
